In [1]:
!nvidia-smi

Sat Sep 14 22:37:45 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:1A:00.0 Off |                  N/A |
| 30%   22C    P8     6W / 250W |  10776MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:1B:00.0 Off |                  N/A |
| 30%   25C    P8    22W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  G

In [2]:
from keras.utils.vis_utils import plot_model
import numpy as np
from keras.models import Sequential
from keras.layers import Activation, LSTM, TimeDistributed, Dense, RepeatVector, CuDNNLSTM, GRU, Bidirectional, Input, CuDNNGRU
from keras.utils import np_utils
from keras.callbacks import TensorBoard
import tensorflow as tf
import os
from keras import backend as K
from keras.models import Model
from keras.layers.core import Dense, Reshape
from keras.layers.wrappers import TimeDistributed
from keras.layers import concatenate
import difflib
from keras.models import load_model
import keras
from keras import losses
import matplotlib.pyplot as plt
import random
from random import choice
import re

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pickle


# In[3]:


os.environ["CUDA_VISIBLE_DEVICES"]="0"
seq_length = 15
val_loss_hist = []

K.clear_session()
keras.backend.clear_session()

X_train=np.load('prepData/X_train_gap_pad_camFam3_v3_chr2_size10.npy')
X_val=np.load('prepData/X_val_gap_pad_camFam3_v3_chr2_size10.npy')
X_test=np.load('prepData/X_test_gap_pad_camFam3_v3_chr2_size10.npy')
y_train=np.load('prepData/y_train_gap_pad_camFam3_v3_chr2_size10.npy')
y_val=np.load('prepData/y_val_gap_pad_camFam3_v3_chr2_size10.npy')
y_test=np.load('prepData/y_test_gap_pad_camFam3_v3_chr2_size10.npy')

y_train1 = np.load('prepData/y_train1_gap_pad_camFam3_v3_chr2_size10.npy')
y_val1 = np.load('prepData/y_val1_gap_pad_camFam3_v3_chr2_size10.npy')
y_test1 = np.load('prepData/y_test1_gap_pad_camFam3_v3_chr2_size10.npy')

Using TensorFlow backend.


In [3]:
print(X_train)

[[[0 1 0 0 0 0]
  [0 1 0 0 0 0]
  [0 0 0 1 0 0]
  ...
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]]

 [[0 1 0 0 0 0]
  [0 0 0 1 0 0]
  [0 1 0 0 0 0]
  ...
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]]

 [[0 0 0 1 0 0]
  [0 1 0 0 0 0]
  [0 0 1 0 0 0]
  ...
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]]

 ...

 [[0 0 0 0 1 0]
  [0 0 1 0 0 0]
  [0 0 0 0 1 0]
  ...
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]]

 [[0 0 1 0 0 0]
  [0 0 0 0 1 0]
  [0 0 0 1 0 0]
  ...
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]]

 [[0 0 0 0 1 0]
  [0 0 0 1 0 0]
  [0 0 0 0 1 0]
  ...
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]
  [1 0 0 0 0 0]]]


In [4]:
nucleotide = ['0', 'A', 'C', 'G', 'T', '-']
def decoder(array):
    result = ""
    size = len(array)
    for i in range(size):
        if array[i].tolist() == [1, 0, 0, 0, 0, 0]:
            result=result+"0" 
        elif array[i].tolist() == [0, 1, 0, 0, 0, 0]:
            result=result+"A"
        elif array[i].tolist() == [0, 0, 1, 0, 0, 0]:
            result=result+"C"
        elif array[i].tolist() == [0, 0, 0, 1, 0, 0]:
            result=result+"G"
        elif array[i].tolist() == [0, 0, 0, 0, 1, 0]:
            result=result+"T"
        elif array[i].tolist() == [0, 0, 0, 0, 0, 1]:
            result=result+"-"
    return result

#model5 = load_model('model/seq2seq_nogap_camFam3_1mut.h5')
def decoderY(array):
    result = ""
    size = len(array)
    
    if array.tolist() == [1, 0, 0, 0, 0, 0]:
        result=result+"0" 
    elif array.tolist() == [0, 1, 0, 0, 0, 0]:
        result=result+"A"
    elif array.tolist() == [0, 0, 1, 0, 0, 0]:
        result=result+"C"
    elif array.tolist() == [0, 0, 0, 1, 0, 0]:
        result=result+"G"
    elif array.tolist() == [0, 0, 0, 0, 1, 0]:
        result=result+"T"
    elif array.tolist() == [0, 0, 0, 0, 0, 1]:
        result=result+"-"
    return result


def printHitMiss(a,b):
    if a==b:
        return 'Hit'
    else:
        return 'Miss'
    
print(X_test.shape)
def accuracy(a, b):
    count = 0
    for i in range(len(a)):
        if a[i] == b[i]:
            count = count+1
    return count/len(a)

def accuracy2(a, b, c):
    count = 0
    count2 =0
    for i in range(len(a)):
        if a[i] != c[i]:
            count2 = count2 +1
        if a[i] != c[i] and b[i]==c[i]:
            count = count+1
    return count/count2

def isMutation(a, b):
    if a!= b:
        print("mutation")

def predict(model):
    x_true=[]
    y_hat_list = []
    y_true = []
    predictions = model.predict(X_test, batch_size=250, verbose=0)
    
    for i, prediction in enumerate(predictions):
        #print(prediction)
        # print(prediction)
        #x_index = np.argmax(testX[i], axis=1)
        #print(prediction[i])
        x_str = decoder(X_test[i])

        #index = np.argmax(prediction)
        index = np.random.choice(6, 3, p=prediction)
        result = [nucleotide[index]]

        print(''.join(x_str), ' -> ', ''.join(result),
              " true: ", ''.join(decoderY(y_test[i])), printHitMiss(''.join(result), ''.join(decoderY(y_test[i]))))
        x_true.append(''.join(x_str[5]))
        y_hat_list.append(''.join(result))
        y_true.append(''.join(decoderY(y_test[i])))
    sm=difflib.SequenceMatcher(None,y_hat_list,y_true)
    sm2=difflib.SequenceMatcher(None,y_hat_list,x_true)
    print()
    print("Percentage of target and prediction being identical: {}".format(accuracy(y_hat_list, y_true)))
    print("Percentage of training and prediction being identical: {}".format(accuracy(y_hat_list, x_true)))
    print("Accuracy given mutation happened : {}".format(accuracy2(x_true, y_hat_list, y_true)))
    return x_true, y_hat_list, y_true


# In[ ]:


def lstm_model(latent_dim, half):
    encoder_inputs = Input(shape=(None, 6))
    
    encoder = Bidirectional(CuDNNLSTM(half, return_state=True))
    encoder_outputs, forward_h, forward_c, backward_h, backward_c = encoder(encoder_inputs)
    state_h = concatenate([forward_h, backward_h])
    state_c = concatenate([forward_c, backward_c])
    
    
    # only keep the states.
    encoder_states = [state_h, state_c]

    # Set up the decoder
    decoder_inputs = Input(shape=(None, 6))
    decoder_lstm = CuDNNLSTM(latent_dim, return_sequences=True, return_state=True)
    decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                         initial_state=encoder_states)
    decoder_dense = Dense(6, activation='softmax')
    decoder_outputs = decoder_dense(decoder_outputs)

    # Define the model that will turn
    # `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
    model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
    
    # inference
    encoder_model = Model(encoder_inputs, encoder_states)

    decoder_state_input_h = Input(shape=(latent_dim,))
    decoder_state_input_c = Input(shape=(latent_dim,))
    decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
    decoder_outputs, state_h, state_c = decoder_lstm(
        decoder_inputs, initial_state=decoder_states_inputs)
    decoder_states = [state_h, state_c]
    decoder_outputs = decoder_dense(decoder_outputs)
    decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

    # Run training
    model.compile(loss='categorical_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy']
                  )
    return model, encoder_model, decoder_model


def modelFit(epoch, batchSize, latent_dim, half, X_train, y_train, y_train1):
    model1, encoder_model1, decoder_model1 = lstm_model(latent_dim, half)
    hist1 = model1.fit([X_train, y_train1], y_train,
          batch_size=batchSize,
          epochs=epoch,
          validation_data=([X_val,y_val1], y_val),
          verbose = 2
         )
    return hist1, model1, encoder_model1, decoder_model1

def grid_search(latent, half,train_size, X_train, y_train, y_train1):
    hist1, model1, encoder_model1, decoder_model1 = modelFit(1, 100, latent, half, X_train, y_train, y_train1)
    hist2 ,model2, encoder_model2, decoder_model2 = modelFit(2, 100, latent, half, X_train, y_train, y_train1)
    hist3 ,model3, encoder_model3, decoder_model3 = modelFit(10, 100, latent, half, X_train, y_train, y_train1)
    #hist4 ,model4, encoder_model4, decoder_model4 = modelFit(30, 100, latent, half, X_train, y_train, y_train1)
    #hist5 ,model5, encoder_model5, decoder_model5 = modelFit(50, 100, latent, half, X_train, y_train, y_train1)
    #hist6 ,model6, encoder_model6, decoder_model6 = modelFit(80, 100, latent, half, X_train, y_train, y_train1)
    #hist7 ,model7, encoder_model7, decoder_model7 = modelFit(100, 100, latent, half, X_train, y_train, y_train1)
    #hist8 ,model8, encoder_model8, decoder_model8 = modelFit(500, 100, latent, half)

    model1.save("models/gap_pad_v2_{}_{}_1.h5".format(train_size,half))
    model2.save("models/gap_pad_v2_{}_{}_2.h5".format(train_size,half))
    model3.save("models/gap_pad_v2_{}_{}_10.h5".format(train_size,half))
    #model4.save("models/_gap_pad_v2_{}_{}_30_double.h5".format(train_size,half))
    #model5.save("models/_gap_pad_v2_{}_{}_50_double.h5".format(train_size,half))
    #model6.save("models/_gap_pad_v2_{}_{}_80_double.h5".format(train_size,half))
    #model7.save("models/_gap_pad_v2_{}_{}_100_double.h5".format(train_size,half))
    #model8.save("_gap_pad_v2_{}_{}_500.h5".format(train_size,half))
    
    encoder_model1.save("models/Egap_pad_v2_{}_{}_1.h5".format(train_size,half))
    encoder_model2.save("models/Egap_pad_v2_{}_{}_2.h5".format(train_size,half))
    encoder_model3.save("models/Egap_pad_v2_{}_{}_10.h5".format(train_size,half))
    #encoder_model4.save("models/E_gap_pad_v2_{}_{}_30_double.h5".format(train_size,half))
    #encoder_model5.save("models/E_gap_pad_v2_{}_{}_50_double.h5".format(train_size,half))
    #encoder_model6.save("models/E_gap_pad_v2_{}_{}_80_double.h5".format(train_size,half))
    #encoder_model7.save("models/E_gap_pad_v2_{}_{}_100_double.h5".format(train_size,half))
    #encoder_model8.save("E_gap_pad_v2_{}_{}_500.h5".format(train_size,half))
    
    decoder_model1.save("models/Dgap_pad_v2_{}_{}_1.h5".format(train_size,half))
    decoder_model2.save("models/Dgap_pad_v2_{}_{}_2.h5".format(train_size,half))
    decoder_model3.save("models/Dgap_pad_v2_{}_{}_10.h5".format(train_size,half))
    #decoder_model4.save("models/D_gap_pad_v2_{}_{}_30_double.h5".format(train_size,half))
    #decoder_model5.save("models/D_gap_pad_v2_{}_{}_50_double.h5".format(train_size,half))
    #decoder_model6.save("models/D_gap_pad_v2_{}_{}_80_double.h5".format(train_size,half))
    #decoder_model7.save("models/D_gap_pad_v2_{}_{}_100_double.h5".format(train_size,half))
    #decoder_model8.save("D_gap_pad_v2_{}_{}_500.h5".format(train_size,half))
    
    count = [i for i in range(len(hist3.history['val_loss']))]
    val_loss_hist.append([hist3.history['val_loss'].index(min(hist3.history['val_loss'])),min(hist3.history['val_loss'])])
    print(val_loss_hist)
    for i, value in zip(count, hist3.history['val_loss']):
        print(i, value)

grid_search(16, 8, 000, X_train, y_train, y_train1)        
grid_search(32, 16, 000, X_train, y_train, y_train1)
grid_search(64, 32, 000, X_train, y_train, y_train1)
grid_search(128, 64, 000, X_train, y_train, y_train1)
grid_search(256, 128, 000, X_train, y_train, y_train1)
grid_search(512, 256, 000, X_train, y_train, y_train1)
grid_search(1024, 512, 000, X_train, y_train, y_train1)
#grid_search(8192, 4096, 000, X_train, y_train, y_train1)

with open('loss_hist.txt', 'wb') as fp:
    pickle.dump(val_loss_hist, fp)

(50000, 15, 6)
Train on 9950000 samples, validate on 50000 samples
Epoch 1/1
 - 1373s - loss: 0.4000 - acc: 0.8836 - val_loss: 0.3295 - val_acc: 0.9153
Train on 9950000 samples, validate on 50000 samples
Epoch 1/2
 - 1329s - loss: 0.4021 - acc: 0.8823 - val_loss: 0.3321 - val_acc: 0.9158
Epoch 2/2
 - 1295s - loss: 0.3443 - acc: 0.9087 - val_loss: 0.3146 - val_acc: 0.9217
Train on 9950000 samples, validate on 50000 samples
Epoch 1/10
 - 1346s - loss: 0.4234 - acc: 0.8699 - val_loss: 0.3417 - val_acc: 0.9115
Epoch 2/10
 - 1286s - loss: 0.3480 - acc: 0.9059 - val_loss: 0.3119 - val_acc: 0.9220
Epoch 3/10
 - 1311s - loss: 0.3279 - acc: 0.9127 - val_loss: 0.3005 - val_acc: 0.9247
Epoch 4/10
 - 1260s - loss: 0.3213 - acc: 0.9146 - val_loss: 0.2959 - val_acc: 0.9265
Epoch 5/10
 - 1254s - loss: 0.3176 - acc: 0.9157 - val_loss: 0.2935 - val_acc: 0.9276
Epoch 6/10
 - 1251s - loss: 0.3154 - acc: 0.9165 - val_loss: 0.2929 - val_acc: 0.9279
Epoch 7/10
 - 1285s - loss: 0.3136 - acc: 0.9170 - val_los

/home/mcb/dlim63/miniconda3/envs/research/lib/python3.6/site-packages/keras/engine/network.py:877: UserWarning: Layer cu_dnnlstm_2 was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'concatenate_1/concat:0' shape=(?, 16) dtype=float32>, <tf.Tensor 'concatenate_2/concat:0' shape=(?, 16) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  '. They will not be included '
/home/mcb/dlim63/miniconda3/envs/research/lib/python3.6/site-packages/keras/engine/network.py:877: UserWarning: Layer cu_dnnlstm_4 was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'concatenate_3/concat:0' shape=(?, 16) dtype=float32>, <tf.Tensor 'concatenate_4/concat:0' shape=(?, 16) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  '. They will not be included '
/home/mcb/dlim63/miniconda3/envs/research/lib/python3.6/site-package

[[9, 0.2844229333251715]]
0 0.3416686093658209
1 0.31185708378255367
2 0.30046474426984787
3 0.29591935010254383
4 0.2934861443191767
5 0.2928774592131376
6 0.28882020369172096
7 0.28866321060061456
8 0.28736401227116587
9 0.2844229333251715
Train on 9950000 samples, validate on 50000 samples
Epoch 1/1
 - 1218s - loss: 0.3228 - acc: 0.9105 - val_loss: 0.2715 - val_acc: 0.9321
Train on 9950000 samples, validate on 50000 samples
Epoch 1/2
 - 1244s - loss: 0.3305 - acc: 0.9093 - val_loss: 0.2714 - val_acc: 0.9321
Epoch 2/2
 - 1198s - loss: 0.2913 - acc: 0.9222 - val_loss: 0.2689 - val_acc: 0.9326
Train on 9950000 samples, validate on 50000 samples
Epoch 1/10
 - 1204s - loss: 0.3270 - acc: 0.9109 - val_loss: 0.2715 - val_acc: 0.9322
Epoch 2/10
 - 1366s - loss: 0.2911 - acc: 0.9225 - val_loss: 0.2692 - val_acc: 0.9326
Epoch 3/10
 - 1214s - loss: 0.2895 - acc: 0.9228 - val_loss: 0.2684 - val_acc: 0.9327
Epoch 4/10
 - 1247s - loss: 0.2888 - acc: 0.9230 - val_loss: 0.2676 - val_acc: 0.9328
Epo

/home/mcb/dlim63/miniconda3/envs/research/lib/python3.6/site-packages/keras/engine/network.py:877: UserWarning: Layer cu_dnnlstm_8 was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'concatenate_7/concat:0' shape=(?, 32) dtype=float32>, <tf.Tensor 'concatenate_8/concat:0' shape=(?, 32) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  '. They will not be included '
/home/mcb/dlim63/miniconda3/envs/research/lib/python3.6/site-packages/keras/engine/network.py:877: UserWarning: Layer cu_dnnlstm_10 was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'concatenate_9/concat:0' shape=(?, 32) dtype=float32>, <tf.Tensor 'concatenate_10/concat:0' shape=(?, 32) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  '. They will not be included '
/home/mcb/dlim63/miniconda3/envs/research/lib/python3.6/site-packa

[[9, 0.2844229333251715], [8, 0.26674772495031357]]
0 0.27153913788497447
1 0.26915460416674614
2 0.2683993786126375
3 0.2675954289287329
4 0.2675661608725786
5 0.2675082699209452
6 0.2675195243358612
7 0.26687554074823855
8 0.26674772495031357
9 0.2667837294638157
Train on 9950000 samples, validate on 50000 samples
Epoch 1/1
 - 1323s - loss: 0.3017 - acc: 0.9182 - val_loss: 0.2673 - val_acc: 0.9333
Train on 9950000 samples, validate on 50000 samples
Epoch 1/2
 - 1434s - loss: 0.3024 - acc: 0.9179 - val_loss: 0.2663 - val_acc: 0.9333
Epoch 2/2
 - 1393s - loss: 0.2861 - acc: 0.9238 - val_loss: 0.2661 - val_acc: 0.9336
Train on 9950000 samples, validate on 50000 samples
Epoch 1/10
 - 1598s - loss: 0.3027 - acc: 0.9180 - val_loss: 0.2680 - val_acc: 0.9330
Epoch 2/10
 - 1571s - loss: 0.2866 - acc: 0.9237 - val_loss: 0.2663 - val_acc: 0.9335
Epoch 3/10
 - 1426s - loss: 0.2856 - acc: 0.9240 - val_loss: 0.2656 - val_acc: 0.9337
Epoch 4/10
 - 1397s - loss: 0.2851 - acc: 0.9242 - val_loss: 0.26

KeyboardInterrupt: 